// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwsvukmtsuajwpewvjfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3c3Z1a210c3VhandwZXd2amZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNjU1MzgsImV4cCI6MjA2Mzc0MTUzOH0.aBucrF9jB49Q7E8teDUOq_9JUWCQR3jtqAc8mFLHSIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);